```{r}
realestate<- read.csv("C:/Users/Nick/Desktop/Realestate.csv", header=TRUE)
pairs(realestate, main="analysis")
summary(realestate)
typeof(realestate)
a1=sub("transaction.date","0",realestate)
a2=sub('house.age','1',a1)
a3=sub('distinction.to.the.nearest.MRT.station','2',a2)
a4=sub('number.of.convenience.stores','3',a3)
a5=sub('latitude','4',a4)
a6=sub("longtitude",'5',a5)
```
```{r}
boxplot(X1.transaction.date~Y.house.price.of.unit.area, data = realestate)
boxplot(X2.house.age~Y.house.price.of.unit.area, data = realestate)
boxplot(X3.distance.to.the.nearest.MRT.station~Y.house.price.of.unit.area, data = realestate)
boxplot(X4.number.of.convenience.stores~Y.house.price.of.unit.area, data = realestate)
boxplot(X5.latitude~Y.house.price.of.unit.area, data = realestate)
boxplot(X6.longitude~Y.house.price.of.unit.area, data = realestate)
```

```{r}
cov(realestate)
cor(realestate)

```

```{r}
library(olsrr)
model=lm(Y.house.price.of.unit.area~X2.house.age+X3.distance.to.the.nearest.MRT.station+X4.number.of.convenience.stores+X1.transaction.date+X5.latitude+X6.longitude,data=realestate)
allpossible=ols_step_all_possible(model)
allpossible
plot(allpossible)
```

```{r}
realestate.res=resid(model)
plot(realestate$X2.house.age,realestate.res, ylab="latitude", xlab="longtitude", main="real estate")
```


```{r}
model=lm(Y.house.price.of.unit.area~X2.house.age+X3.distance.to.the.nearest.MRT.station+X4.number.of.convenience.stores+X1.transaction.date+X5.latitude+X6.longitude,data=realestate)
best=ols_step_best_subset(model)
best
plot(best)
```

```{r}
summary=lm(Y.house.price.of.unit.area~X2.house.age+X3.distance.to.the.nearest.MRT.station+X4.number.of.convenience.stores+X1.transaction.date+X5.latitude+X6.longitude,data=realestate)
```

```{r}
summary(lm(Y.house.price.of.unit.area~X2.house.age+X3.distance.to.the.nearest.MRT.station+X4.number.of.convenience.stores+X1.transaction.date+X5.latitude+X6.longitude,data=realestate))
plot(lm(Y.house.price.of.unit.area~X2.house.age+X3.distance.to.the.nearest.MRT.station+X4.number.of.convenience.stores+X1.transaction.date+X5.latitude+X6.longitude,data=realestate))
```



```{r}
houseage1=realestate$X2.house.age
transactiondate=realestate$X1.transaction.date
latitude=realestate$X5.latitude
longtitude=realestate$X6.longitude


z2<-(houseage1-mean(houseage1))
z3<-(transactiondate-mean(transactiondate))
z1<-(latitude-mean(latitude))
ys<-(longtitude-mean(longtitude))
realestatemodel1=lm(ys~z1+z2)
realestatemodel2=lm(ys~z1+z3)
vif(realestatemodel1)
vif(realestatemodel2)
```

