```{r}
real estate<- read.csv("C:/Users/Desktop/Real estate.csv", header=TRUE)
pairs(real estate, main="analysis")
typeof(real estate)
table(real estate)
a1=sub("transaction date","0",real estate)
a2=sub('house age','1',a1)
a3=sub('distinction to the nearest MRT station','2',a2)
a4=sub('number of convenience stores','3',a3)
a5=sub('latitude','4',a4)
a6=sub("longtitude",'5',a5)
a7=sub("house price of unit area",'6',a6)
```

```{r}
cov(real estate)
cor(real estate)
```

```{r}
library(olsrr)
model=lm(transaction date~house age+Length1+Length2+Length3+latitude+longtitude,data=real estate)
allpossible=ols_step_all_possible(model)
allpossible
plot(allpossible)
```

```{r}
real estate.res=resid(model)
plot(real estate$house age,real estate.res, ylab="latitude", xlab="longtitude", main="real estate")
```


```{r}
model=lm(house age~transaction date+Length1+Length2+Length3+latitude+longtitude,data=fishdata)
best=ols_step_best_subset(model)
best
plot(best)
```

```{r}
summary=lm(house age~transaction date+Length1+Length2+Length3+latitude+longtitude,data=fishdata)
```

```{r}
summary(lm(house age~transaction date+Length1+Length2+Length3+latitude+longtitude,data=fishdata))
plot(lm(house age~transaction date+Length1+Length2+Length3+latitude+longtitude,data=fishdata))
```



```{r}
house age1=real estate$house age1
house age3=real estate$house age3
transaction date=real estate$transaction date
latitude=real estate$latitude
longtitude=real estate$longtitude



z2<-(house age1-mean(house age1))/s1
z3<-(transaction date-mean(transaction date))/s3
z1<-(latitude-mean(latitude))/s3
ys<-(longtitude-mean(longtitude))/sy
real estate model1=lm(ys~z1+z2)
real estate model2=lm(ys~z1+z3)
real estate model3=lm(ys~z3+z4)
vif(real estate hmodel1)
vif(real estate model2)
vif(real estate model3)
```

